FROM golang:latest

WORKDIR /app
# webpに変換する用
RUN  apt-get update -y
RUN apt-get install libwebp-dev -y
RUN go install github.com/cosmtrek/air@latest

ENV GOCACHE=/tmp/.cache
COPY go.mod go.sum ./
RUN go mod download

CMD ["/bin/bash"]