// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
	"time"
)

type Category struct {
	ID   string
	Name string
}

type Comment struct {
	ID        string
	VideoID   string
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    sql.NullString
}

type History struct {
	ID        string
	UserID    string
	VideoID   string
	WatchedAt time.Time
}

type LikeDislike struct {
	ID        string
	UserID    string
	VideoID   sql.NullString
	CommentID sql.NullString
	IsLike    bool
	CreatedAt time.Time
}

type Playlist struct {
	ID          string
	Name        string
	Description sql.NullString
	UserID      string
	CreatedAt   time.Time
}

type PlaylistVideo struct {
	PlaylistID string
	VideoID    string
}

type Report struct {
	ID        string
	UserID    string
	VideoID   sql.NullString
	CommentID sql.NullString
	Reason    string
	CreatedAt time.Time
}

type Subscription struct {
	UserID    string
	ChannelID string
}

type Tag struct {
	ID      int32
	TagName string
}

type User struct {
	ID              string
	Name            string
	ProfileImageUrl string
}

type Video struct {
	ID                string
	VideoUrl          string
	ThumbnailImageUrl string
	Title             string
	Description       sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
	IsPrivate         bool
	IsAdult           bool
	IsAd              bool
	UploaderID        string
	WatchCount        int32
	IsExternalCutout  bool
}

type VideoCategory struct {
	VideoID    string
	CategoryID string
}

type VideoTag struct {
	VideoID string
	TagID   int32
}
