// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type Node interface {
	IsNode()
	GetID() string
}

type PostCommentInput struct {
	VideoID string `json:"videoID"`
	Text    string `json:"text"`
}

type PostCommentPayload struct {
	ID        string `json:"id"`
	VideoID   string `json:"videoID"`
	Text      string `json:"text"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	User      *User  `json:"user,omitempty"`
}

type UploadVideoInput struct {
	Video          graphql.Upload  `json:"video"`
	ThumbnailImage *graphql.Upload `json:"thumbnailImage,omitempty"`
	Title          string          `json:"title"`
	Description    *string         `json:"description,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

type UserInput struct {
	Name string `json:"name"`
}

type UserPayload struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Video struct {
	ID                string  `json:"id"`
	VideoURL          string  `json:"videoURL"`
	Title             string  `json:"title"`
	ThumbnailImageURL string  `json:"thumbnailImageURL"`
	Description       *string `json:"description,omitempty"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
	Uploader          *User   `json:"uploader"`
}

func (Video) IsNode()            {}
func (this Video) GetID() string { return this.ID }

type VideoPayload struct {
	ID                string  `json:"id"`
	VideoURL          string  `json:"videoURL"`
	Title             string  `json:"title"`
	ThumbnailImageURL string  `json:"thumbnailImageURL"`
	Description       *string `json:"description,omitempty"`
	CreatedAt         string  `json:"createdAt"`
	UpdatedAt         string  `json:"updatedAt"`
	Uploader          *User   `json:"uploader"`
}
