package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	model "github.com/yuorei/video-server/app/domain/models"
	"github.com/yuorei/video-server/graph/generated"
)

// ID is the resolver for the id field.
func (r *commentResolver) ID(ctx context.Context, obj *model.Comment) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Video is the resolver for the video field.
func (r *commentResolver) Video(ctx context.Context, obj *model.Comment) (*model.Video, error) {
	panic(fmt.Errorf("not implemented: Video - video"))
}

// User is the resolver for the user field.
func (r *commentResolver) User(ctx context.Context, obj *model.Comment) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// PostComment is the resolver for the postComment field.
func (r *mutationResolver) PostComment(ctx context.Context, input model.PostCommentInput) (*model.PostCommentPayload, error) {
	panic(fmt.Errorf("not implemented: PostComment - postComment"))
}

// Video is the resolver for the video field.
func (r *postCommentPayloadResolver) Video(ctx context.Context, obj *model.PostCommentPayload) (*model.Video, error) {
	panic(fmt.Errorf("not implemented: Video - video"))
}

// User is the resolver for the user field.
func (r *postCommentPayloadResolver) User(ctx context.Context, obj *model.PostCommentPayload) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// CommentsByVideo is the resolver for the commentsByVideo field.
func (r *queryResolver) CommentsByVideo(ctx context.Context, videoID string) ([]*model.Comment, error) {
	panic(fmt.Errorf("not implemented: CommentsByVideo - commentsByVideo"))
}

// Comment is the resolver for the comment field.
func (r *queryResolver) Comment(ctx context.Context, id string) (*model.Comment, error) {
	panic(fmt.Errorf("not implemented: Comment - comment"))
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// PostCommentPayload returns generated.PostCommentPayloadResolver implementation.
func (r *Resolver) PostCommentPayload() generated.PostCommentPayloadResolver {
	return &postCommentPayloadResolver{r}
}

type commentResolver struct{ *Resolver }
type postCommentPayloadResolver struct{ *Resolver }
